name: Dockerfile Lint
on:
  push:
    branches: [ main ]
    paths:
        - "./Dockerfile"
        - "./test/Dockerfile"
  pull_request:
    branches: [ main ]

jobs:
  hadolint:
    runs-on: ubuntu-20.04
    name: "Hadolint"
    steps:
      - uses: actions/checkout@v2
      - uses: jbergstroem/hadolint-gh-action@v1
        with:
        # ignore warnings (but still fail on errors) from hadolint
          error_level: 1