name: Dockerfile Lint
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  hadolint:
    runs-on: ubuntu-20.04
    name: "Hadolint"
    steps:
      - uses: actions/checkout@v2
      - uses: jbergstroem/hadolint-gh-action@v1
        with:
          # dockerfile: "Dockerfile test/Dockerfile"
        # ignore warnings (but still fail on errors) from hadolint
          error_level: 1

  docker:
    needs: hadolint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build an image from Dockerfile
        run: |
          docker build . -t bad-dockerfile -f bad-dockerfile/Dockerfile
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'bad-dockerfile'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: joeshiett/bad-dockerfile:latest 